import json

topics_data = [
    {
        "title": "Introduction to DevOps",
        "content": "<p><strong>Definition:</strong> DevOps is a combination of cultural philosophies, practices, and tools that increases an organization's ability to deliver applications and services at high velocity. It is a portmanteau of 'Development' and 'Operations'.</p><p><strong>Why it exists:</strong> Historically, developers (Dev) focused on writing code quickly and adding new features, while IT operations (Ops) focused on stability and keeping servers running. This created a 'wall of confusion' where Devs threw code over the wall, and Ops struggled to deploy it safely. DevOps breaks down this silo.</p><ul><li><strong>Goal:</strong> Shorten the systems development life cycle and provide continuous delivery with high software quality.</li><li><strong>Key Pillars:</strong> Culture, Automation, Lean IT, Measurement, and Sharing (CALMS).</li></ul><p><strong>Exam Tip:</strong> Always mention that DevOps is NOT just a tool (like Jenkins or Docker). It is fundamentally a cultural shift backed by tooling.</p>"
    },
    {
        "title": "Need and Benefits of DevOps",
        "content": "<p><strong>The Need:</strong> Without DevOps, companies face slow deployment cycles, high failure rates of new releases, finger-pointing between teams, and manual, error-prone deployment processes.</p><p><strong>Core Benefits:</strong></p><ul><li><strong>Speed & Agility:</strong> Move faster to innovate for customers and adapt to changing markets.</li><li><strong>Rapid Delivery:</strong> Increase the frequency and pace of releases so you can improve your product faster.</li><li><strong>Reliability:</strong> Ensure the quality of application updates and infrastructure changes so you can reliably deliver at a more rapid pace while maintaining a positive experience for end users. (Achieved via CI/CD).</li><li><strong>Scale:</strong> Operate and manage infrastructure and development processes at scale (via Automation and Infrastructure as Code).</li><li><strong>Improved Collaboration:</strong> Teams share responsibilities and combine their workflows, reducing inefficiencies.</li><li><strong>Security:</strong> Move quickly while retaining control and preserving compliance (DevSecOps).</li></ul>"
    },
    {
        "title": "DevOps Culture and Collaboration",
        "content": "<p><strong>Definition:</strong> The cultural aspect is the most critical part of DevOps. It shifts the mindset from 'my job is done when the code is written' to 'my job is done when the code is running successfully in production and generating value.'</p><p><strong>Key Characteristics:</strong></p><ul><li><strong>Shared Responsibility:</strong> Developers don't just write code; they help support it in production. Ops teams don't just manage servers; they work with devs to automate deployments.</li><li><strong>Blameless Post-Mortems:</strong> When outages occur, the focus is on finding the systemic failure that allowed the error to happen, rather than firing the person who made the mistake.</li><li><strong>Transparency:</strong> Open communication across teams using tools like Slack, Jira, and shared monitoring dashboards.</li><li><strong>Continuous Learning:</strong> Fostering an environment where experimenting and failing fast is encouraged to drive innovation.</li></ul>"
    },
    {
        "title": "DevOps Principles",
        "content": "<p><strong>The Principles:</strong> The core principles of DevOps can be remembered using the acronym <strong>CAMS</strong> or <strong>CALMS</strong>:</p><ul><li><strong>Culture:</strong> Embracing collaboration, shared responsibility, and blamelessness.</li><li><strong>Automation:</strong> Removing manual toil. Automating builds, testing, deployments, and infrastructure provisioning.</li><li><strong>Lean:</strong> Using lean principles to eliminate waste, optimize the whole system, and deliver value rapidly in small batches.</li><li><strong>Measurement:</strong> Tracking everything. If you can't measure it, you can't improve it. Using KPIs like deployment frequency and MTTR.</li><li><strong>Sharing:</strong> Sharing knowledge, tools, and processes across teams to break down silos.</li></ul><p><strong>Exam Tip:</strong> If asked about principles, write down CALMS and expand on each letter with a 1-line explanation.</p>"
    },
    {
        "title": "DevOps Lifecycle",
        "content": "<p><strong>Definition:</strong> The DevOps lifecycle is a continuous, infinite loop that represents the phases software goes through from ideation to production and back to ideation based on user feedback.</p><p><strong>The Infinite Loop:</strong> Unlike the traditional Waterfall model which is linear (goes in one direction and ends), the DevOps lifecycle is cyclical. It emphasizes that software is never truly 'finished'.</p><p><strong>Why an infinite loop?</strong> Because once the software is Deployed and Operated, we Monitor it. The data we get from Monitoring (bugs, user behavior, performance metrics) directly feeds back into the Plan phase for the next version.</p><p><strong>Exam Tip:</strong> Draw an infinity symbol (∞) in the exam. Label the left side Dev (Plan, Code, Build, Test) and the right side Ops (Release, Deploy, Operate, Monitor).</p>"
    },
    {
        "title": "DevOps Lifecycle Stages",
        "content": "<p><strong>The 8 Stages Explained:</strong></p><ol><li><strong>Plan:</strong> Define business value and requirements. (Tools: Jira, Trello).</li><li><strong>Code:</strong> Writing the software and pushing to version control. (Tools: Git, VS Code).</li><li><strong>Build:</strong> Compiling the code and downloading dependencies to create a runnable artifact. (Tools: Maven, Gradle, npm).</li><li><strong>Test:</strong> Running automated unit, integration, and security tests. (Tools: JUnit, Selenium, SonarQube).</li><li><strong>Release:</strong> Packaging the validated code so it is ready for deployment.</li><li><strong>Deploy:</strong> Pushing the release into the production environment. (Tools: Jenkins, Ansible, Docker).</li><li><strong>Operate:</strong> Managing the application in production and ensuring servers are running. (Tools: Kubernetes, Terraform).</li><li><strong>Monitor:</strong> Collecting metrics and logs to ensure the system is healthy and gathering user feedback. (Tools: Prometheus, Grafana, ELK).</li></ol>"
    },
    {
        "title": "Continuous Integration (CI)",
        "content": "<p><strong>Definition:</strong> Continuous Integration is a software development practice where developers regularly merge their code changes into a central repository, after which automated builds and tests are run.</p><p><strong>The Process:</strong></p><ul><li>Developer commits code to Git.</li><li>The CI server (like Jenkins or GitHub Actions) detects the commit.</li><li>The CI server automatically pulls the code, compiles it, and runs unit tests.</li><li>If tests fail, the build is marked as 'broken' and the team is notified immediately to fix it.</li></ul><p><strong>Benefits:</strong> CI prevents 'Integration Hell'. By integrating code constantly (multiple times a day), bugs are found and fixed immediately while the context is fresh in the developer's mind, rather than weeks later during a massive merge.</p>"
    },
    {
        "title": "Continuous Delivery (CD)",
        "content": "<p><strong>Definition:</strong> Continuous Delivery is a software engineering approach in which teams produce software in short cycles, ensuring that the software can be reliably released at any time.</p><p><strong>Key Concept:</strong> It is the logical next step after CI. Once the code is built and passes automated tests (CI), Continuous Delivery automatically deploys the code to a staging or testing environment that mimics production.</p><p><strong>The Human Element:</strong> In Continuous Delivery, the code is 100% ready to go to production. However, it does <strong>not</strong> go to production automatically. A human being (like a Release Manager or Product Owner) must push a button to authorize the final deployment to live customers.</p><p><strong>Exam Tip:</strong> Emphasize 'Release Readiness'. CD means the software is always in a deployable state.</p>"
    },
    {
        "title": "Continuous Deployment",
        "content": "<p><strong>Definition:</strong> Continuous Deployment is the most advanced stage of the CI/CD pipeline. In this practice, every change that passes all stages of your production pipeline is released to your customers automatically. There is no human intervention.</p><p><strong>How it works:</strong> Developer writes code -> Pushes to Git -> CI server builds and tests it -> Quality gates check security and coverage -> The deployment tool automatically pushes it to production servers.</p><p><strong>Requirements:</strong> To achieve Continuous Deployment, you must have an incredibly robust, trustworthy automated testing suite and flawless monitoring. If your tests are bad, you will automatically deploy bugs to your customers.</p><p><strong>Benefits:</strong> Extremely fast feedback loop. Code written in the morning can be generating revenue in the afternoon.</p>"
    },
    {
        "title": "CI vs CD vs Continuous Deployment",
        "content": "<p><strong>The Final Distinction (Memorize this for the exam):</strong></p><ul><li><strong>Continuous Integration (CI):</strong> Focuses on the Code & Build phases. Automatically merging, building, and testing code. <em>Goal: Ensure the code works together.</em></li><li><strong>Continuous Delivery (CD):</strong> Includes CI, plus deploying to a staging environment. The software is <em>ready</em> to be released at any moment. <em>Goal: Eliminate the technical stress of releasing. Requires a manual click to go to production.</em></li><li><strong>Continuous Deployment:</strong> Includes Delivery, but removes the manual click. Every passing change goes straight to production automatically. <em>Goal: Minimize time between writing code and customers using it.</em></li></ul>"
    },
    {
        "title": "Automation in DevOps",
        "content": "<p><strong>Definition:</strong> Automation is the process of using technology to perform tasks with reduced human assistance. In DevOps, 'Automate Everything' is a core mantra.</p><p><strong>What do we automate?</strong></p><ul><li><strong>Code Builds & Testing:</strong> Triggered automatically on every commit.</li><li><strong>Infrastructure as Code (IaC):</strong> Instead of manually clicking through AWS to create servers, we write scripts (Terraform/Ansible) that automatically spin up servers.</li><li><strong>Deployments:</strong> Scripts automatically move code from staging to production.</li><li><strong>Monitoring Alerts:</strong> Systems automatically page engineers if CPU usage hits 90%.</li></ul><p><strong>Why Automate?</strong> Humans are bad at doing the same repetitive task perfectly 100 times. Machines do it perfectly every time. Automation reduces errors, increases speed, and frees up humans to do creative problem-solving.</p>"
    },
    {
        "title": "DevOps Metrics and DORA Metrics",
        "content": "<p><strong>Definition:</strong> To know if DevOps is working, you must measure it. The industry standard is DORA (DevOps Research and Assessment) metrics, which categorize teams into Low, Medium, High, and Elite performers.</p><p><strong>The 4 Key DORA Metrics:</strong></p><ol><li><strong>Deployment Frequency (Throughput):</strong> How often an organization successfully releases to production. Elite teams deploy multiple times a day.</li><li><strong>Lead Time for Changes (Throughput):</strong> The amount of time it takes a commit to get into production. Elite teams take less than an hour.</li><li><strong>Change Failure Rate (Stability):</strong> The percentage of deployments causing a failure in production requiring remediation (e.g., hotfix, rollback). Elite teams are between 0-15%.</li><li><strong>Time to Restore Service (Stability):</strong> How long it takes an organization to recover from a failure in production (MTTR). Elite teams recover in less than an hour.</li></ol>"
    },
    {
        "title": "Quality Gates",
        "content": "<p><strong>Definition:</strong> A Quality Gate is a milestone or checkpoint within a CI/CD pipeline where specific quality criteria must be met before the software can proceed to the next stage.</p><p><strong>Examples of Quality Gates:</strong></p><ul><li><strong>Code Coverage:</strong> The pipeline fails if unit tests cover less than 80% of the code.</li><li><strong>Security Scans:</strong> The pipeline fails if static analysis (SAST) detects a high-severity vulnerability like SQL injection.</li><li><strong>Performance Checks:</strong> The pipeline fails if load testing shows API response times exceed 200ms.</li></ul><p><strong>Exam Tip:</strong> Describe Quality Gates as the 'automated gatekeepers' that protect the production environment from bad code. They enforce standards objectively, removing human bias from code reviews.</p>"
    },
    {
        "title": "DevOps Tools and Their Purpose",
        "content": "<p><strong>Exam Strategy:</strong> Don't just list tools; list their categories and what problem they solve.</p><ul><li><strong>Version Control (Git):</strong> Tracks who changed what code and when.</li><li><strong>Code Repositories (GitHub, GitLab, Bitbucket):</strong> Central hubs for hosting Git repos and collaborating via Pull Requests.</li><li><strong>CI/CD Servers (Jenkins, GitLab CI, GitHub Actions):</strong> The engine that runs the automated pipelines, executing scripts when code is pushed.</li><li><strong>Build Tools (Maven, Gradle, npm):</strong> Compiles raw source code into executable artifacts (like a .jar file).</li><li><strong>Configuration Management (Ansible, Chef, Puppet):</strong> Automates the installation of software and configuration of servers.</li><li><strong>Infrastructure as Code (Terraform, CloudFormation):</strong> Provisions cloud infrastructure (VPCs, EC2 instances) using code.</li><li><strong>Containerization (Docker):</strong> Packages an application and its dependencies into a standard unit for consistent deployment.</li><li><strong>Orchestration (Kubernetes):</strong> Manages thousands of Docker containers, handling scaling and self-healing.</li><li><strong>Monitoring (Prometheus, Grafana, ELK Stack):</strong> Collects logs and metrics to visualize system health.</li></ul>"
    },
    {
        "title": "Monitoring and Feedback",
        "content": "<p><strong>Definition:</strong> Monitoring is the systematic collection, analysis, and use of information to ensure systems are operating as expected. Feedback is routing that information back to the developers.</p><p><strong>The Three Pillars of Observability:</strong></p><ol><li><strong>Metrics:</strong> Numeric data measured over time (e.g., CPU is at 85%, memory usage, requests per second).</li><li><strong>Logs:</strong> Immutable, timestamped records of discrete events (e.g., 'User logged in', 'Database connection failed at line 42').</li><li><strong>Traces:</strong> Following a single user's request as it travels through a complex network of microservices to find bottlenecks.</li></ol><p><strong>Why it matters:</strong> Without monitoring, you are flying blind. You only know your app is broken when angry customers call you. With proactive monitoring, you can fix issues before the customer even notices.</p>"
    },
    {
        "title": "Introduction to Git",
        "content": "<p><strong>Definition:</strong> Git is a free and open-source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. It was created by Linus Torvalds in 2005 for Linux kernel development.</p><p><strong>Key Features:</strong></p><ul><li><strong>Distributed:</strong> Every developer has a full, independent local copy of the entire project history. You don't need a network connection to commit changes or view history.</li><li><strong>Branching:</strong> Git makes creating branches incredibly cheap and fast, encouraging non-linear development.</li><li><strong>Data Integrity:</strong> Everything in Git is checksummed (using SHA-1 hashes) before it is stored. It is impossible to change the contents of a file without Git knowing about it.</li></ul><p><strong>Exam Tip:</strong> Always mention that Git tracks <em>changes</em> to files (snapshots), not just storing multiple copies of the same file.</p>"
    },
    {
        "title": "Version Control System (VCS)",
        "content": "<p><strong>Definition:</strong> A Version Control System is a software tool that helps teams manage changes to source code over time. It keeps track of every modification to the code in a special kind of database.</p><p><strong>Why do we need it?</strong></p><ul><li><strong>Collaboration:</strong> Prevents developers from overwriting each other's code when working on the same file.</li><li><strong>History & Reversion:</strong> If a new bug is introduced, VCS allows you to instantly roll back the code to an older, working version.</li><li><strong>Traceability:</strong> It answers: Who made this change? When did they make it? And most importantly, WHY did they make it (via the commit message).</li></ul><p><strong>Types of VCS:</strong> Centralized (like SVN, where there is one central server) and Distributed (like Git, where everyone has a full copy).</p>"
    },
    {
        "title": "Git vs GitHub vs GitLab",
        "content": "<p><strong>This is a classic exam question!</strong> Ensure you can clearly distinguish them.</p><ul><li><strong>Git:</strong> The actual command-line tool and software installed on your local laptop. It is the engine that does the version controlling. It works entirely offline.</li><li><strong>GitHub:</strong> A for-profit company (owned by Microsoft) that provides a cloud-based hosting service for Git repositories. It provides a visual interface, issue tracking, and Pull Requests to make collaborating with Git easier over the internet.</li><li><strong>GitLab:</strong> Similar to GitHub, it is a web-based Git repository manager, but it heavily emphasizes built-in CI/CD pipelines and can be self-hosted on a company's own private servers.</li></ul><p><strong>Analogy:</strong> Git is to GitHub what video recording is to YouTube. Git is the tool; GitHub is the platform where you upload and share the results.</p>"
    },
    {
        "title": "Git Repository",
        "content": "<p><strong>Definition:</strong> A repository (or 'repo') is the most basic element of Git. It's a folder that contains all of your project files, as well as the entire version history of those files.</p><p><strong>The .git folder:</strong> When you initialize a repository, Git creates a hidden directory called <code>.git</code>. This folder is the actual database where Git stores all the snapshots, commits, branches, and tags. If you delete the <code>.git</code> folder, your project becomes a normal, un-tracked folder again and all history is lost.</p><p><strong>Types of Repositories:</strong></p><ul><li><strong>Local Repository:</strong> The repository residing on your personal computer.</li><li><strong>Remote Repository:</strong> The repository hosted on a server or cloud service (like GitHub) used to share code with others.</li></ul>"
    },
    {
        "title": "Working Directory, Staging Area and Repository",
        "content": "<p><strong>The Three Trees (Crucial Mental Model):</strong></p><ol><li><strong>Working Directory:</strong> This is your current workbench. It contains the actual files you see and edit on your computer's hard drive right now.</li><li><strong>Staging Area (The Index):</strong> A hidden file that acts as a 'waiting room' or a 'loading dock'. When you are ready to make a commit, you selectively pick which modified files from your Working Directory should be grouped into the next snapshot. You do this using <code>git add</code>.</li><li><strong>Local Repository (HEAD):</strong> The database where Git permanently stores the snapshots you committed from the Staging Area. You move things here using <code>git commit</code>.</li></ol><p><strong>Exam Tip:</strong> Draw three boxes. Arrow from Box 1 to Box 2 is 'git add'. Arrow from Box 2 to Box 3 is 'git commit'.</p>"
    },
    {
        "title": "Basic Git Workflow",
        "content": "<p><strong>The Daily Sequence:</strong> This is exactly what a developer types every day.</p><ol><li><strong>Modify files</strong> in your working directory.</li><li>Run <strong><code>git status</code></strong> to review what you changed.</li><li>Run <strong><code>git add [filename]</code></strong> (or <code>git add .</code>) to move the changes to the Staging Area.</li><li>Run <strong><code>git commit -m \"Description of changes\"</code></strong> to permanently record the staged changes as a snapshot in your Local Repository.</li><li>Run <strong><code>git push origin main</code></strong> to upload those local commits to the remote server (GitHub) so your team can see them.</li></ol>"
    },
    {
        "title": "Git Configuration",
        "content": "<p><strong>Why configure?</strong> Git relies heavily on accountability. Every commit must be stamped with the name and email of the author. If you don't configure this, Git won't let you commit.</p><p><strong>Commands:</strong></p><ul><li><code>git config --global user.name \"Sunaina Mohapatra\"</code></li><li><code>git config --global user.email \"sunaina@example.com\"</code></li></ul><p><strong>Levels of Config:</strong></p><ul><li><strong>--system:</strong> Applies to all users on the computer.</li><li><strong>--global:</strong> Applies to your specific user account (most common).</li><li><strong>--local:</strong> Applies only to the specific repository you are currently in.</li></ul>"
    },
    {
        "title": "git init",
        "content": "<p><strong>Definition:</strong> <code>git init</code> is a one-time command you use during the initial setup of a new repository. Executing this command creates a new subdirectory named <code>.git</code> that houses all of your necessary repository files — a Git repository skeleton.</p><p><strong>Usage:</strong> Open a terminal, navigate to your project folder, and type <code>git init</code>. Your folder is now a local Git repository. At this point, nothing in your project is tracked yet until you use <code>git add</code>.</p>"
    },
    {
        "title": "git status",
        "content": "<p><strong>Definition:</strong> <code>git status</code> is your compass. It displays the state of the working directory and the staging area.</p><p><strong>What it tells you:</strong></p><ul><li>Which branch you are currently on.</li><li>Whether your branch is ahead or behind the remote branch.</li><li><strong>Untracked files:</strong> Brand new files Git has never seen before.</li><li><strong>Modified files (not staged):</strong> Tracked files you've edited but haven't added to the staging area yet.</li><li><strong>Changes to be committed:</strong> Files currently sitting in the staging area waiting for a <code>git commit</code>.</li></ul><p><strong>Exam Tip:</strong> Mention that <code>git status</code> does NOT show commit history (that is <code>git log</code>). It only shows the CURRENT state.</p>"
    },
    {
        "title": "git add",
        "content": "<p><strong>Definition:</strong> The <code>git add</code> command adds a change in the working directory to the staging area. It tells Git that you want to include updates to a particular file in the next commit.</p><p><strong>Variants:</strong></p><ul><li><code>git add index.html</code>: Stages a single specific file.</li><li><code>git add .</code> (dot): Stages ALL new, modified, and deleted files in the current directory and subdirectories.</li><li><code>git add -p</code>: (Patch mode) Allows you to interactively review changes chunk by chunk and decide whether to stage them. (Advanced but highly professional!).</li></ul><p><strong>Key Concept:</strong> <code>git add</code> does not affect the repository history in any way; changes are not recorded until you run <code>git commit</code>.</p>"
    },
    {
        "title": "git commit",
        "content": "<p><strong>Definition:</strong> The <code>git commit</code> command captures a snapshot of the project's currently staged changes. Committed snapshots can be thought of as 'safe' versions of a project—Git will never change them unless you explicitly ask it to.</p><p><strong>The Commit Message:</strong> Every commit requires a message. Good commit messages are imperative and clear. E.g., <code>git commit -m \"Add user authentication form\"</code>.</p><p><strong>What is inside a commit?</strong> Under the hood, a commit contains:</p><ul><li>A unique SHA-1 hash (e.g., <code>a3f89b1</code>) to identify it.</li><li>The author's name and timestamp.</li><li>A pointer to the parent commit(s).</li><li>A snapshot of the actual file tree.</li></ul>"
    },
    {
        "title": "git log",
        "content": "<p><strong>Definition:</strong> <code>git log</code> lets you view the chronological commit history for a repository. It allows you to see who made a commit, when they made it, the commit message, and the commit hash.</p><p><strong>Useful Flags:</strong></p><ul><li><code>git log --oneline</code>: Condenses each commit to a single line showing just the hash and the message. Great for a quick overview.</li><li><code>git log --graph</code>: Draws a text-based graphical representation of the commit history on the left hand side, showing branch merges.</li><li><code>git log -p</code>: Shows the actual code differences (patches) introduced in each commit.</li></ul>"
    },
    {
        "title": "git clone",
        "content": "<p><strong>Definition:</strong> <code>git clone</code> is a command for downloading an existing Git repository from a remote server (like GitHub) to your local machine.</p><p><strong>What it does exactly:</strong></p><ol><li>Creates a new directory named after the repo.</li><li>Initializes a <code>.git</code> folder inside it.</li><li>Downloads all the data for that repository (every branch, every commit in history).</li><li>Checks out a working copy of the latest version of the default branch (usually `main`).</li><li>Sets up a remote connection called <code>origin</code> pointing back to the URL you cloned from.</li></ol>"
    },
    {
        "title": "git push",
        "content": "<p><strong>Definition:</strong> <code>git push</code> is used to upload local repository content to a remote repository. Pushing is how you transfer commits from your local repository to a remote repo (like GitHub).</p><p><strong>Syntax:</strong> <code>git push [remote-name] [branch-name]</code> (e.g., <code>git push origin main</code>).</p><p><strong>The Rule of Push:</strong> You can only push if your local branch is up-to-date with the remote branch. If your teammate pushed code to GitHub while you were working, GitHub will reject your push. You must <code>git pull</code> their changes, merge them with yours, and then <code>git push</code> the combined result.</p>"
    },
    {
        "title": "git pull",
        "content": "<p><strong>Definition:</strong> The <code>git pull</code> command is used to fetch and download content from a remote repository and immediately update the local repository to match that content.</p><p><strong>Under the hood:</strong> <code>git pull</code> is actually a combination of two commands run one after the other:</p><ol><li><strong><code>git fetch</code>:</strong> Downloads the data from the remote server.</li><li><strong><code>git merge</code>:</strong> Immediately attempts to merge the downloaded data into your current working branch.</li></ol><p><strong>Risk:</strong> Because it automatically merges, it can sometimes trigger unexpected merge conflicts directly in your working directory.</p>"
    },
    {
        "title": "git fetch",
        "content": "<p><strong>Definition:</strong> <code>git fetch</code> downloads commits, files, and refs from a remote repository into your local repo, <strong>but does not integrate them into your working files.</strong></p><p><strong>Why use fetch instead of pull?</strong> Fetch is the safe operation. It allows you to see what everyone else has been working on and review their code (using <code>git log</code> or <code>git diff</code>) before you decide to merge their work into your own branch. It updates your local copy of the remote branches (e.g., <code>origin/main</code>), but leaves your actual <code>main</code> branch alone until you explicitly run a merge.</p>"
    },
    {
        "title": "Git Branches",
        "content": "<p><strong>Definition:</strong> A branch in Git is simply a lightweight movable pointer to a specific commit. Branching allows you to diverge from the main line of development and continue to do work without messing with that main line.</p><p><strong>Why use branches?</strong></p><ul><li><strong>Isolation:</strong> You can work on an experimental feature or a risky bug fix in isolation. If it goes wrong, you can just delete the branch. The main codebase is unaffected.</li><li><strong>Parallel Development:</strong> Multiple developers can work on the same repository simultaneously on their own branches, entirely unaware of each other until it's time to merge.</li></ul><p><strong>Exam Tip:</strong> Mention that creating branches in Git is nearly instantaneous and takes almost zero disk space, which is why branching is highly encouraged in Git workflows.</p>"
    },
    {
        "title": "Branch Creation and Switching",
        "content": "<p><strong>Creating a branch:</strong> Use <code>git branch new-feature</code>. This creates a new pointer at your current commit, but it does NOT switch you to that branch.</p><p><strong>Switching branches:</strong> Use <code>git checkout new-feature</code> (or the newer command <code>git switch new-feature</code>). This updates your working directory to look exactly like the files in that branch.</p><p><strong>Warning:</strong> Before switching branches, you generally want to have a clean working directory (commit or stash your changes), otherwise Git might prevent you from switching to avoid losing uncommitted work.</p>"
    },
    {
        "title": "Git Merge",
        "content": "<p><strong>Definition:</strong> Merging is Git's way of putting a forked history back together again. The <code>git merge</code> command lets you take the independent lines of development created by <code>git branch</code> and integrate them into a single branch.</p><p><strong>How to do it:</strong></p><ol><li>Switch to the branch you want to receive the changes (e.g., <code>git checkout main</code>).</li><li>Run the merge command targeting the branch with the new code (e.g., <code>git merge feature/login</code>).</li></ol><p><strong>Fast-Forward vs 3-Way Merge:</strong> If `main` hasn't changed since you created your feature, Git just moves the pointer forward (Fast-Forward). If both branches have new commits, Git creates a new special 'merge commit' that ties both histories together.</p>"
    },
    {
        "title": "Merge Conflicts",
        "content": "<p><strong>Definition:</strong> A merge conflict occurs when Git cannot automatically resolve differences in code between two commits. This usually happens when two developers change the exact same lines in a file, or if one developer deletes a file while another modifies it.</p><p><strong>How to resolve it:</strong></p><ul><li>Git stops the merge process and marks the files as 'conflicted' in your working directory.</li><li>You must open the files in a text editor. Git injects conflict markers (<code>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</code>, <code>=======</code>, <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt; branch-name</code>) highlighting the competing changes.</li><li>You manually edit the file to keep the code you want, delete the conflict markers, save the file.</li><li>Finally, run <code>git add</code> on the resolved file and <code>git commit</code> to finalize the merge.</li></ul>"
    },
    {
        "title": ".gitignore",
        "content": "<p><strong>Definition:</strong> <code>.gitignore</code> is a plain text file placed in the root of your repository that contains a list of file patterns that Git should completely ignore. Ignored files will not show up in <code>git status</code> and cannot be accidentally added via <code>git add .</code></p><p><strong>What belongs in .gitignore?</strong></p><ul><li><strong>Secrets:</strong> API keys, passwords, `.env` files. (CRITICAL for security).</li><li><strong>Compiled code:</strong> `.class`, `.jar`, `.exe`, or `node_modules/` folders (because they can be regenerated from source).</li><li><strong>System files:</strong> Mac's `.DS_Store` or Windows `Thumbs.db`.</li><li><strong>Logs:</strong> Locally generated `.log` files.</li></ul>"
    },
    {
        "title": "git diff",
        "content": "<p><strong>Definition:</strong> <code>git diff</code> is a command-line utility that takes two input data sets and outputs the changes between them. It shows exactly which lines were added, modified, or deleted.</p><p><strong>Common Uses:</strong></p><ul><li><code>git diff</code>: Shows unstaged changes in your working directory compared to the staging area. (What have I changed but not yet staged?)</li><li><code>git diff --staged</code>: Shows changes in the staging area compared to the last commit. (What am I about to commit?)</li><li><code>git diff branchA branchB</code>: Compares the tips of two different branches.</li></ul><p><strong>Exam Tip:</strong> It is the best tool for reviewing your own work before you commit.</p>"
    },
    {
        "title": "git reset vs git revert",
        "content": "<p><strong>This is a critical distinction for exams! Both are used to undo changes, but they do it very differently.</strong></p><ul><li><strong>git revert:</strong> This is the SAFE way to undo. It creates a brand <strong>new</strong> commit that contains the exact inverse changes of the bad commit. The old bad commit stays in history, and a new 'undo' commit is added on top. <em>Use this if the bad commit has already been pushed to GitHub and shared with others.</em></li><li><strong>git reset:</strong> This is the DANGEROUS way to undo. It literally moves the branch pointer backward in time, rewriting history and erasing commits as if they never happened. <em>Use this ONLY for local commits on your personal machine that have not been pushed to GitHub yet.</em> If you reset shared history, you will break your teammates' repositories.</li></ul>"
    },
    {
        "title": "Fork and Pull Request",
        "content": "<p><strong>Definition:</strong> These are not core Git commands, but rather features provided by platforms like GitHub/GitLab.</p><p><strong>Fork:</strong> A fork is a personal, server-side copy of someone else's repository. You use it when you want to contribute to an open-source project where you don't have write access. You fork their repo, clone your fork, make changes, and push to your fork.</p><p><strong>Pull Request (PR):</strong> Once your changes are in your fork (or your own branch), you open a Pull Request. This is a formal notification to the original repository owners saying, 'I have made some changes. Please review them and pull them into your main branch.' PRs are where code reviews happen, CI tests run, and discussions take place before merging.</p>"
    },
    {
        "title": "GitHub/GitLab Collaboration Workflow",
        "content": "<p><strong>The Industry Standard Workflow (Feature Branch Workflow):</strong></p><ol><li><strong>Pull:</strong> <code>git pull origin main</code> to ensure your local main is up to date.</li><li><strong>Branch:</strong> <code>git checkout -b feature/new-login</code> to isolate your work.</li><li><strong>Work:</strong> Write code, <code>git add</code>, and <code>git commit</code>.</li><li><strong>Push:</strong> <code>git push origin feature/new-login</code> to upload your branch to GitHub.</li><li><strong>Pull Request:</strong> Go to GitHub and open a Pull Request against the main branch.</li><li><strong>Review & Automate:</strong> Teammates review the code. CI/CD runs automated tests against the PR.</li><li><strong>Merge:</strong> Once approved and tests pass, a maintainer clicks 'Merge'. The branch is merged into main and deployed.</li></ol>"
    }
]

import json

new_topics_js = "const topics = " + json.dumps([[t["title"], t["content"]] for t in topics_data], indent=2) + ";"

with open('index.html', 'r') as f:
    content = f.read()

import re
pattern = re.compile(r'const topics\s*=\s*\[.*?\];', re.DOTALL)
content = re.sub(pattern, new_topics_js, content)

with open('index.html', 'w') as f:
    f.write(content)

print("Deeply expanded topics written to index.html.")
